Name:           deckery-tray
Version:        0.3.0
Release:        1%{?dist}
Summary:        Deckery system tray — service monitor and control for KDE Plasma

License:        GPL-3.0-only
URL:            https://github.com/Plasma-Deckery/deckery

# Source is generated by `make srpm` (see .copr/Makefile) — not fetched from URL.
Source0:        %{url}/archive/v%{version}/deckery-%{version}.tar.gz

BuildArch:      noarch

BuildRequires:  systemd-rpm-macros

# Runtime dependencies — all available as Fedora RPMs.
Requires:       python3
# GObject Introspection bindings (gi.repository.Gtk, GdkPixbuf, GLib, Gio, Notify)
Requires:       python3-gobject3
# GTK3 runtime + typelib (gi.repository.Gtk 3.0, GdkPixbuf 2.0)
Requires:       gtk3
# Ayatana AppIndicator for the system tray icon (gi.repository.AyatanaAppIndicator3)
Requires:       libayatana-appindicator-gtk3
# Desktop notifications (gi.repository.Notify 0.7)
Requires:       libnotify
# Process tree inspection for game detection
Requires:       python3-psutil
# gdbus for deckery-hud D-Bus calls (Toggle)
Requires:       glib2

Requires:       makima-deckery >= %{version}
Requires:       deckery-hud >= %{version}

%description
deckery-tray is a GTK3 system tray applet that monitors and controls the
Deckery input stack. It shows the current state of makima-deckery (active,
paused, gaming mode), detects running Steam games, and lets the user toggle
the HUD overlay, pause remapping, and configure per-application profiles.

Includes an onboarding wizard for first-run setup and a self-update checker.

%prep
%autosetup -n deckery-%{version}

%build
# Pure Python — nothing to compile.

%install
# Tray Python source
install -dm755 %{buildroot}%{_prefix}/lib/deckery-tray
install -pm644 tray/*.py %{buildroot}%{_prefix}/lib/deckery-tray/

# Onboarding wizard (setup/ subpackage)
install -dm755 %{buildroot}%{_prefix}/lib/deckery-tray/setup
install -pm644 tray/setup/*.py %{buildroot}%{_prefix}/lib/deckery-tray/setup/

# Tray icons (SVG — used by the tray applet at runtime)
install -dm755 %{buildroot}%{_prefix}/lib/deckery-tray/icons
install -pm644 tray/icons/*.svg %{buildroot}%{_prefix}/lib/deckery-tray/icons/

# App icon (for .desktop and KDE launcher)
install -Dm644 tray/icons/tray-ok.svg \
    %{buildroot}%{_datadir}/icons/hicolor/scalable/apps/deckery.svg

# Default configs — installed to system path; makima-deckery falls back here
# if ~/.config/makima/ is empty or absent.
install -dm755 %{buildroot}%{_datadir}/deckery/configs
install -pm644 "configs/Steam Deck.toml" \
    %{buildroot}%{_datadir}/deckery/configs/
for f in configs/Steam\ Deck::*.toml; do
    [ -f "$f" ] && install -pm644 "$f" %{buildroot}%{_datadir}/deckery/configs/
done
# VDF template for Steam Input onboarding (lives in configs/, read via MAKIMA_CONFIGS path)
install -pm644 configs/desktop_neptune.vdf \
    %{buildroot}%{_datadir}/deckery/configs/

# Desktop launcher
install -Dm644 deckery.desktop \
    %{buildroot}%{_datadir}/applications/deckery.desktop

# Systemd user service
install -Dm644 packaging/deckery-tray.service \
    %{buildroot}%{_userunitdir}/deckery-tray.service

%post
%systemd_user_post deckery-tray.service

%preun
%systemd_user_preun deckery-tray.service

%files
%license LICENSE
%doc README.md
%{_prefix}/lib/deckery-tray/
%{_datadir}/icons/hicolor/scalable/apps/deckery.svg
%{_datadir}/deckery/
%{_datadir}/applications/deckery.desktop
%{_userunitdir}/deckery-tray.service

%changelog
* Sat Aug 16 2026 Philipp Schimmelfennig <philipp@plasma-deckery.dev> - 0.3.0-1
- Initial RPM packaging
- GTK3 system tray applet with Ayatana AppIndicator
- Game detection via psutil process tree inspection
- Onboarding wizard for first-run Steam Input setup
- No distrobox, no podman — runs python3 directly via systemd user service
- Default configs installed to /usr/share/deckery/configs/
